#include "_GPIO.h"

int main()
{
	_GPIO_ENABLE_CLK(GPIO_PORT_A);

	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_0, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_1, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_2, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_3, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_4, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_5, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_6, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_7, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_8, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_9, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_10, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_11, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_12, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_13, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_14, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);
	_GPIO_SET_MODE(GPIO_PORT_A, GPIO_PIN_15, GPIO_OUT_PUSH_PULL, GPIO_OUT_S_2MHZ);



	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_0, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_1, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_2, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_3, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_4, HIGH);

	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_5, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_6, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_7, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_8, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_9, HIGH);

	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_10, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_11, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_12, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_13, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_14, HIGH);
	_GPIO_WRITE_PIN(GPIO_PORT_A, GPIO_PIN_15, HIGH);

	return 0;
}
